spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shareCalender?useUnicode=true&characterEncoding=utf8
    username: caluser
    password: alalqqqq1
    driver-class-name: org.mariadb.jdbc.Driver
    # 커넥션 풀 개수 설정
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate  # 개발 시에는 'create', 실제 운영 시에는 'validate' or 'none'으로 설정
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# 포트번호 지정
server:
  port: 61314
  address: 0.0.0.0